### ISSUE TITLE
101 Lab Questions/Bugs - "unable to connect to the server"

### ISSUE THREAD

**Issue by SDToews** [BCDevOps/devops-platform-workshops#102]
## Lab Questions or Bugs

Working through the Lab instructions (Setup page) I install OC then run _oc version_ which returns a version number and an "unable to connect to the server" error.  

The next page (Adding User Access) instructs us to run _oc projects_, which returns "unable to connect to the server" error.

I resolved this by running _oc login <<etc>>_, but this instruction is not in the Lab instructions

## Information for debugging

Please add instructions on how to login to the OC server on the Setup page of the Lab instructions.

## Error Messages or Screen Shots

unable to connect to the server

**Comment by mtspn** [comment]
Added section to OCP101 lab content detailing OC login: https://github.com/BCDevOps/devops-platform-workshops/blob/master/101-lab/content/01_setup.md
