### ISSUE TITLE
OCP 201: Outreach to Community

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/devops-platform-workshops#103]
## Summary

In the effort of a new 201 course we are reaching out to the community to see what the majority wants to see in the workshop. The workshop will undoubtedly cover concepts of CI/CD and how it integrates into our platform services such as Sysdig/Aqua etc.

## To Do

- send a correspondence to the community via most likely survey but will need to confer with Martha. 
- receive feedback from community and covert it into a small report here so that it is easily consumed.

**Comment by mitovskaol** [comment]
@marthaedwards I think we can close this ticket now.
