### ISSUE TITLE
OCP 201 Lab: Shell assumptions

### ISSUE THREAD

**Issue by conbrad** [BCDevOps/devops-platform-workshops#144]
Note the snippet under: https://github.com/BCDevOps/devops-platform-workshops/blob/master/openshift-201/pipelines.md#running-a-pipeline

Assumes a `bash` shell I believe. I can create a PR to state that as a note if wanted.

**Comment by mtspn** [comment]
Thanks @conbrad, I've added a line into the prerequisites for 'Intro to Pipelines' lab exercises to address this.
