### ISSUE TITLE
101 Lab - typo

### ISSUE THREAD

**Issue by rustyjux** [BCDevOps/devops-platform-workshops#181]
## Lab Typo

On the [overview page](https://github.com/BCDevOps/devops-platform-workshops/blob/master/101-lab/content/00_overview.md) it says 'happy bath' but probably was meant to be 'happy path'. I kind of like happy bath though.

**Comment by mtspn** [comment]
Thanks @rustyjux. Happy bath is a great typo, but is now fixed!
