### ISSUE TITLE
System Set Up , CA Certificates Unable to Install

### ISSUE THREAD

**Issue by gnyi** [BCDevOps/devops-platform-workshops#193]
## Unable to Download and Install the CA Certificates for openshift-cli

I am preparing for the upcoming Openshift 101 training. During the system set up, I was unable to move forward because I got an error shown in the attached snip. While I tried to read the details in sslcerts documents, do not understand and was unable to solve. I installed the system into my office workstation which is in the bc government network. Your support would be appreciated. Thanks and looking forward to hearing from you.

## Error Messages or Screen Shots
<img width="846" alt="image" src="https://github.com/BCDevOps/devops-platform-workshops/assets/60405933/219154e1-99ef-45a7-929d-aa2633937847">

**Comment by mtspn** [comment]
My understanding is that this issue was resolved during the OpenShift 101 lab and workshop, so I'm closing this ticket. Please feel free to re-open if that was not the case.
