### ISSUE TITLE
OCP101 - Lab - Deployments/Triggers Section (content confusion)

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/devops-platform-workshops#25]
Pertaining to this section:

> start of section
## Versioning a Deployment Configuration
At this point in time, your deployment configuration has undergone many changes, such as adding environment variables and adding health checks. Review the deployment configuration History tab:

- Select Deployment #1, right-click, and open in a new tab
- Select your latest deployment version, right-click, and open in a new tab
- Compare the differences - this can be done through the UI or by comparing the YAML

## Changing Deployment Configuration Triggers
While reviewing the different deployment versions, take note of the Trigger column.
> end of section
---
It looks like this instruction is a bit misleading. A student explaining that while viewing the replication controllers the triggers column is not visible. 

Based on this instruction:  ___" While reviewing the different deployment versions, take note of the Trigger column."___

I'd suggest changing this to something like:

"After reviewing the different deployment versions (aka replication controllers), view the Deployment Config and take note of the Trigger Column"

**Comment by mtspn** [comment]
Appears to refer to antiquated content descriptions
