### ISSUE TITLE
OCP101 - dev labs - missing images in a few sections

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/devops-platform-workshops#27]
In 'Changing Deployment Configurations' Section there is a broken image here:..
![Screen Shot 2019-09-11 at 3 04 04 PM](https://user-images.githubusercontent.com/21046727/64738958-9e2dba00-d4a5-11e9-800e-1d4e51abf850.png)

In just above 'Exploring Health Checks' there is a broken image.

![Screen Shot 2019-09-11 at 3 04 57 PM](https://user-images.githubusercontent.com/21046727/64738959-9ec65080-d4a5-11e9-82cc-b656b8943456.png)

**Comment by mitovskaol** [comment]
@mtspn Can. you please check if the issue still exists, this ticket is quite old.

**Comment by mtspn** [comment]
These broken images look to be resolved, so I'll close this ticket.
