### ISSUE TITLE
Update 101 workshop content

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/devops-platform-workshops#45]
Tasks:
- include a brief introduction on the lab content (rocketchat app + mongodb)
- add title for route section
- make mongo URL available in text form (tbd)
- Typo in Autoscaling lab: 'Review the deployment configuraiton and try to add or remove __repicas__'
- Error in Persitant Storage Lab: Scale down mongodb-[username] to __1 pods__
- explain why rolling deployment will fail for db

**Comment by jefkel** [comment]
Please add: 
Update persistent storage labs to use netapp-file-standard and netapp-block-standard storageClasses instead of gluster-* storage classes.

**Comment by patricksimonian** [comment]
reminder to update storage class lab and slides to mention preference is to use net-app-file-standard inmost cases. RWO or RWX .  block storage is tailored for performance i do believe. @jefkel @cvarjao
