### ISSUE TITLE
Meeting: OpenShift 101 Review

### ISSUE THREAD

**Issue by cvarjao** [BCDevOps/devops-platform-workshops#49]
- Move `Resource Requests and Limits` lab earlier as part of  troubleshooting deployment issues before deploying mongoDB
- Remove Registry Console Lab
- Start session with creating a branch of the docs/labs, and make changes on the fly
- Create a RocketChat base images caching dependencies to help speed up build time
- Create a diagram of the the lifecycle of application (from Build to Pod)

- Look into maybe move away from gitbook into something else (e.g.: Gastby)

Nice to have:
- A slide about container and images and relationship to docker/docker hub. Comparing to traditional way

**Comment by patricksimonian** [comment]
![build-to-deployment](https://user-images.githubusercontent.com/21046727/73794849-22871f00-475e-11ea-8736-1804d55744b1.png)
 @cvarjao what do you think?
