### ISSUE TITLE
OCP101 Workshops - Resource Tuning

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/devops-platform-workshops#67]
We need to add a slide in the miro board to explain the importance of resource tuning and how to do it. This should be coupled with the lab demonstration of resource tuning.

**Comment by patricksimonian** [comment]
Based on feedback from the September 16th session. We are thinking of experimenting with trimming down lecture material and provide more practical demonstrations instead. Sections we are thinking of trimming down:

- openshift architecture
- onboarding

**Comment by patricksimonian** [comment]
another crazy idea is to revamp the content and focus on applying whats learned to building a simple s2i build/deploy of a multi stack app (frontend backend)

**Comment by mitovskaol** [comment]
Resource Tuning will be included in Openshift 201 curriculum
