### ISSUE TITLE
OCP4 ARO Cluster requires RWX storage class

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/devops-platform-workshops#68]
## What
Currently we only have one storage class that can be utilized as RWO.

@stewartshea 

## Ask

Have atleast another storage class that can be utilized as RWO or RWX

## Impact

The OCP 101 Persistent Configuration Lab asks students to test/debug provisioning storage of those different read/write types. This lab is not usable without the storage class as described above ! :)

**Comment by patricksimonian** [comment]
@stewartshea could we get a summary of what needs to be done as far as seeing if RWX storage is provision-able? Do we need to rope in Justin and or Olena?

**Comment by stewartshea** [comment]
@patricksimonian I need to investigate the right approach to provisioning azure-file and investigate the permission structure. I'm actively working on this and will have some findings for you within a day or two.

**Comment by stewartshea** [comment]
@patricksimonian I've created a storageclass called `azure-file`. Take it for a spin.
