### ISSUE TITLE
OCP101 Lab: Introduction to Shared Services

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/devops-platform-workshops#87]
## Summary

The ocp101 lab should have a good introduction on all the shared services the platform provides. Things like sysdig,  artifactory, etc. 

## To do:

- add content to create a sysdig team
- update rc deploy content to view metrics through sysdig
- demonstrate how to create alerts with sysdig
- add content on creating artifact repos
- unknowns (this sounds like an epic)

**Comment by mtspn** [comment]
Current version of Openshift101 covers these topics, or they will be added to 201.
